# Generated by Django 6.0.7 on 2026-08-26 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('paid', 'PAID'), ('pending', 'PENDING'), ('not access', 'not_access'), ('not delivered', 'not_delivered'), ('delivered', 'DELIVERED'), ('processing', 'PROCESSING')], default='pending', max_length=20),
        ),
    ]
