# Generated by Django 5.2.5 on 2026-06-22 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailproduct',
            name='price',
        ),
    ]
