# Generated by Django 5.2.5 on 2026-06-22 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_remove_detailproduct_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailproduct',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
