# Generated by Django 6.0.7 on 2026-07-23 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0002_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
