# Generated by Django 6.0.7 on 2026-07-25 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0003_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
