# Generated by Django 6.0.7 on 2026-09-07 14:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0007_commentproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentproduct',
            name='rating',
            field=models.PositiveIntegerField(default=5, max_length=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
