# Generated by Django 5.2.5 on 2026-07-11 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_session_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('draft', 'Draft'), ('paid', 'Paid'), ('sent', 'Sent')], default='draft', max_length=20),
        ),
    ]
