# Generated by Django 5.2.5 on 2026-07-11 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('draft', 'Draft'), ('paid', 'Paid'), ('sent', 'Sent'), ('delivered', 'Delivered')], default='draft', max_length=20),
        ),
    ]
