# Generated by Django 5.2.5 on 2026-07-03 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartlist',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
