# Generated by Django 5.2.5 on 2026-07-07 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cartlist_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartlist',
            name='price',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=10),
            preserve_default=False,
        ),
    ]
